LogMsgLength: 100
LogRotateSizeInMB: 600
NumberofLogFiles: 1
NumberofLogs: 400000
TimeToSleep: 0
client_id: a4237d5c-6b2c-4ebf-bc6e-c282222a4b6e
client_key: ruYe47eWWACMb2VBDqpyQamWwT8yj9wj
client_secret: GEq4K4TbZYxu3TyvrWGmTftfajXyCgXRwXfCGbSUpE5c9QM2qwart9uRDbc5NaBv
portal_url: uat.opsramp.net
AWS_TOKEN: 3PANz2fF9ESbCGT3FftVw8zqPRTTHDmf
AZURE_TOKEN: ZTNvHpPx6NHAHrebWUH7ePYJPJFG2Ns4
GCP_TOKEN: cqVvCaXsyWPe7zpck7gpDQTPccRgbkp2
AWS_BUCKETNAME : logs-validation
GOOGLECHAT_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAAAV4jeHC8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=tp_r--y2kXuf9VkUSCd3m4hhBmYHTVCUGMr6gJ4wmkU%3D
SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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 
Portal_Name: UAT
