LogMsgLength: 100
LogRotateSizeInMB: 600
NumberofLogFiles: 1
NumberofLogs: 400000
TimeToSleep: 0
client_id: 54b3a69c-2e5f-46b6-a03f-02b35d81367b
client_key: Kw9MHruFeSxbzsecdVJfz5X8gfXAt2Cw
client_secret: kTpPHmw3gtWa3qrmpdvVJUBWucETCaYAqDs7sjX8tED3f3sbHaD3a23pkUQTUAnF
portal_url: uat.opsramp.net
AWS_TOKEN: 7QNdyKBHTM3xYcPfgR3UwDWVR5shcKTV
AZURE_TOKEN: 9QpRhNwXwDxsPRMbzXkbSWuUmEU5x6w5
GCP_TOKEN: wARyKdUXAtjp9bKhbBhrQqQFaGkxM7hK
AWS_BUCKETNAME : logsvalidation-uat
GOOGLECHAT_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAAAV4jeHC8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=tp_r--y2kXuf9VkUSCd3m4hhBmYHTVCUGMr6gJ4wmkU%3D
SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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 
Portal_Name: UAT
ArchivalFileSize : 20M
