LogMsgLength: 100
LogRotateSizeInMB: 600
NumberofLogFiles: 1
NumberofLogs: 100000
TimeToSleep: 0
client_id: 10687630-9040-4b76-99a7-7fea4d1c3e9b
client_key: ZGY6UXCR4sYcYT3KUJjyCcEMXm6MfRHC
client_secret: vvPr3Pny6QDvhvAh36EybEJEJu4Z6XRRHNZtAFhvddBwZVueUttbdzf5QFSQKa88
portal_url: uat.opsramp.net
AWS_TOKEN: QwWUb9uZzNfHxkt7fK4KVf6czZ82ddBx
AZURE_TOKEN: SKWM2cxzc7Sk7F9HcrGdyBmCjCE8wHc5
GCP_TOKEN: mXVSG5UQ6EVARngFSkszmubEp5jgY3cf
AWS_BUCKETNAME : logs-validation
GOOGLECHAT_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAAAV4jeHC8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=tp_r--y2kXuf9VkUSCd3m4hhBmYHTVCUGMr6gJ4wmkU%3D
SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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  
Portal_Name: UAT