---
global:
  ignore_older: 4h
inputs:
  logcount:
    type: file
    include:
    - /home/LogsAutomation/*.log
    exclude:
    - ''
    regex: ''
    custom_formatting: ''
    time_format: ''
    filters:
    - key: ''
      include: ''
    masking:
    - text: ''
      placeholder: ''
